const tasks = [
    {
        id: 1,
        projectId: 1,
        tick: true,
        title: 'Tech requirements',
        taskCreated: '2024-01-04',
        duoDate: '2025-06-16',
        status: 'Approved',
        description: 'This redesign proposal aims to enhance the user experience, reflect Infoware Technologies commitment to digital innovation',
        userId: 4,
    },
    {
        id: 2,
        projectId: 1,
        tick: false,
        title: 'UI Design Draft',
        taskCreated: '2024-01-12',
        duoDate: '2025-06-17',
        status: 'Re work',
        description: 'Initial draft of the UI mockups for the dashboard and user profile pages.',
        userId: 3,
    },
    {
        id: 3,
        projectId: 3,
        tick: false,
        title: 'Backend Integration',
        taskCreated: '2024-01-07',
        duoDate: '2025-07-03',
        status: 'Pending',
        description: 'Connect frontend with the REST API endpoints and test CRUD operations.',
        userId: 3,
    },
    {
        id: 4,
        projectId: 2,
        tick: false,
        title: 'Team Feedback Review',
        taskCreated: '2024-01-09',
        duoDate: '2025-06-18',
        status: 'Approved',
        description: 'Gather and address feedback from team members on the current implementation.',
        userId: 2,
    },
    {
        id: 5,
        projectId: 4,
        tick: true,
        title: 'Deployment Setup',
        taskCreated: '2024-01-12',
        duoDate: '2025-06-19',
        status: 'Re work',
        description: 'Configure CI/CD pipelines and prepare production server for deployment.',
        userId: 6,
    },
    {
        id: 6,
        projectId: 6,
        tick: false,
        title: 'UI Design Draft',
        taskCreated: '2024-01-12',
        duoDate: '2025-07-03',
        status: 'In progress',
        description: 'Initial draft of the UI mockups for the dashboard and user profile pages.',
        userId: 2,
    },
    {
        id: 7,
        projectId: 1,
        tick: true,
        title: 'QA Testing',
        taskCreated: '2024-02-01',
        duoDate: '2025-06-20',
        status: 'In progress',
        description: 'Perform end-to-end testing of all new features.',
        userId: 5,
    },
    {
        id: 8,
        projectId: 1,
        tick: false,
        title: 'Bug Fixes',
        taskCreated: '2024-02-05',
        duoDate: '2025-06-21',
        status: 'Pending',
        description: 'Fix all bugs found during testing.',
        userId: 3,
    },
    {
        id: 9,
        projectId: 2,
        tick: false,
        title: 'Documentation',
        taskCreated: '2024-02-10',
        duoDate: '2025-06-22',
        status: 'In progress',
        description: 'Write documentation for new features and APIs.',
        userId: 1,
    },
    {
        id: 10,
        projectId: 3,
        tick: true,
        title: 'Code Review',
        taskCreated: '2024-02-15',
        duoDate: '2025-06-23',
        status: 'Approved',
        description: 'Review code before merging to main branch.',
        userId: 4,
    },
    {
        id: 11,
        projectId: 4,
        tick: false,
        title: 'UX Improvements',
        taskCreated: '2024-02-20',
        duoDate: '2025-06-24',
        status: 'Re work',
        description: 'Improve UX based on user feedback.',
        userId: 2,
    },
    {
        id: 12,
        projectId: 5,
        tick: false,
        title: 'Database Migration',
        taskCreated: '2024-02-25',
        duoDate: '2025-06-25',
        status: 'Pending',
        description: 'Migrate database to new schema.',
        userId: 6,
    },
    {
        id: 13,
        projectId: 6,
        tick: true,
        title: 'Performance Optimization',
        taskCreated: '2024-03-01',
        duoDate: '2025-06-26',
        status: 'Approved',
        description: 'Optimize app performance and reduce load time.',
        userId: 3,
    }
];

export default tasks;